/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "gridchatappdb-dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:77645af9-b812-405d-b442-064cab6036fb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_uj1FXvgVi",
    "aws_user_pools_web_client_id": "6nvj51v414kqjkf9g9mdbkbdfc",
    "oauth": {}
};


export default awsmobile;
